server:
  port: 8081
spring:
  application:
    name: customer-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:customer;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}
    username: ${DATASOURCE_USER:sa}
    password: ${DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
